### ISSUE TITLE
Slow glossary command

### ISSUE THREAD

**Issue by N4M3Z** [erichs/composure#14]
Running glossary command seems very slow on my system (zsh 5.0.7 x86_64-apple-darwin14.0.0). I only have one user defined function. Is this expected?
```
cite                                                                  creates one or more meta keywords for use in your functions
draft                                                                 wraps command from history into a new function, default is last
                                                                      command
glossary                                                              displays help summary for all functions, or summary for a group of
                                                                      functions
metafor                                                               prints function metadata associated with keyword
ping.google                                                           Test connection via Google DNS (8.8.8.8)
reference                                                             displays apidoc help for a specific function
revise                                                                loads function into editor for revision
write                                                                 writes one or more composed function definitions to stdout
15.5386480000s elapsed
```

**Comment by erichs** [comment]
@N4M3Z: yikes! so, frameworks like ohmyzsh and tools like rvm add a *lot* of shell functions, which will slow `glossary` down. My `glossary` run is certainly faster, but not, say an order of magnitude faster.

One obvious approach to making this faster is to pre-render the reference and glossary data, following a `draft` or `revise`.

Given four functions: `clone`, `commits`, `tophogs` and `weather`, split among two groups `git` and `misc`, I imagine the pre-rendered glossary data could be kept in the following directory structure within the `.composure` directory:

```shell
.
├── clone.inc
├── commits.inc
├── glossary
│   ├── clone.gloss
│   ├── commits.gloss
│   ├── git.list
│   ├── misc.list
│   ├── tophogs.gloss
│   └── weather.gloss
├── tophogs.inc
├── weather.inc
```

the lists themselves could be trivially sorted when `glossary <group>` is called, and the `.gloss` files displayed. I suspect this would make things much faster indeed.

**Comment by N4M3Z** [comment]
I am using zgen myself, but I do have nvm, rvm and assorted plugins installed, so I guess that would be the issue behind this. Given your comment on speeding things up, are you planning to do this change yourself?

**Comment by erichs** [comment]
It may be a few weeks until I can give this some attention. If you're willing to work on it sooner, I'd happily take a PR!

**Comment by N4M3Z** [comment]
I would be willing to work on it sooner, but I am not sure where to start? If you can drop a few more suggestions, I could look into the code and figure out if I have to power to tackle this.

**Comment by N4M3Z** [comment]
Another minor suggestion would be to alias `composure.sh` to `composure.plugin.zsh` as this will make this package automatically compatible with zgen, antigen and oh-my-zsh.

**Comment by erichs** [comment]
@N4M3Z: interesting suggestion! I'll consider that.

What I was thinking above is to rewrite the `glossary()` function, [extracting the portion that generates the glossary lines](https://github.com/erichs/composure/blob/master/composure.sh#L330-335), and putting that into a new function, let's call it `_gloss_function()`. This function would take a function name as an argument. It would generate the `.gloss` file inside the `$(_get_composure_dir)/glossary` directory. If it detected one or more lines of `group` metadata for the function, it would also add the function name to a unique, sorted list stored in the same directory, with a `groupname.list` convention. So, if a function specified:

```
myfunc() {
  group foo
  group bar
}
```

Then `myfunc` would appear in `glossary/foo.list` and `glossary/bar.list`.

`_gloss_function()` could then be called at the bottom of the `revise()` function, like:

```shell
revise() {
  ...
    printf '%s\n' 'zero-length file, revision aborted!'
  fi
  command rm "$temp"
  _gloss_function "$func"
}
```

`glossary()` could then be re-written, something like:

```
glossary() {
  typeset glossdir=$(_get_composure_dir)/glossary
  typeset group="$1"
  if [ -n "$group" ]; then 
    for func in $(cat $glossdir/$group.list); do
      cat $glossdir/$func.gloss
    done
  else
    for func in $(ls $glossdir/*.gloss | sort); do
      cat $glossdir/$func.gloss
    done
  fi
}
```
