### ISSUE TITLE
functions not loaded; glossary does not list functions in repo

### ISSUE THREAD

**Issue by dotmpe** [erichs/composure#21]
Edit: See fix attached.

Given

- installed composure.sh using basher
- symlinked ~/.local/composure to checkout (a submodule in ~/.conf)
- can draft/revise functions OK

When I synchronize the setup with another box, same setup, I do not see the functions. Even though the checkout has the files. I can revise them and then they load,  but the initial shell env does not. 

To test I've used:

```
$ export LOAD_COMPOSED_FUNCTIONS=1
$ . ~/.basher/cellar/bin/composure.sh
$ glossary
cite          creates one or more meta keywords for use in your functions
draft         wraps command from history into a new function, default is last command
glossary      displays help summary for all functions, or summary for a group of
              functions
metafor       prints function metadata associated with keyword
reference     displays apidoc help for a specific function
revise        loads function into editor for revision
write         writes one or more composed function definitions to stdout
```

<del>What could cause composure.sh to fail to load the functions initially?</del>

**Comment by dotmpe** [comment]
My bad. I failed to reload the shell env at the source box, which was also broken.

The find command was missing the trailing '/', or ``-H``.

**Comment by erichs** [comment]
Thanks!
