### ISSUE TITLE
Glossary (_typeset_functions, _shell) fail in script

### ISSUE THREAD

**Issue by dotmpe** [erichs/composure#23]
(Re)-using composure 'glossary' inside a script fails when ``_shell`` does not detect bash, but the scriptname instead. Causing ``_typeset_functions`` to switch to z-shell mode resulting in a long list of typeset errors:
```
typeset: cannot use `-f' to make functions
[...]
typeset: `[1]="_typeset_functions_about"': not a valid identifier
[etc]
```

A typical offending `ps -p $$` line as used by ``_shell`` (detects shell 'help' iso. 'bash' here)
```
81515 ttys004    0:00.08 bash /Users/berend/.local/composure/Composure/main.sh c help
```

Solution (BSD Darwin and GNU) add `ps` option to select command-name (w/o args):
```
ps -p $$ -o comm
```

**Comment by erichs** [comment]
closed via previous merge.
