### ISSUE TITLE
typeset -f fails on GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)

### ISSUE THREAD

**Issue by earchibald-lv** [erichs/composure#25]
Updating all the `typeset -f` references to `declare -f` resolved everything.

```
(ansible) DESKTOP-R0H5FVK:composure earchibald$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by erichs** [comment]
Strange. In my experience these are [direct synonyms](https://tldp.org/LDP/abs/html/declareref.html), and in fact `typeset` is better supported. I'm not able to repro this directly, but I'll keep an ear out for any others that might be having issues with the `typeset` builtin.
