### ISSUE TITLE
Write function outputs cite function as well as parameters

### ISSUE THREAD

**Issue by mrazick** [erichs/composure#27]
Hello,

Is the below line correct? I suspect it should read `typeset -f "$@"`

https://github.com/erichs/composure/blob/55fdb9fa3cd0f181208a46d90da4d87d5b7e4351/composure.sh#L526

**Comment by 5c0tt-b0t** [comment]
hello @mrazick
same problem here, did your suggestion fix this???
Either way, would be nice to fix this if possible.
@erichs THANK YOU for composure, I love it!

**Comment by 5c0tt-b0t** [comment]
Ok, just tested and it indeed fixes that problem! thanks @mrazick 👍 
I was wondering if you knew (or better yet, the man himself @erichs)
whether this "if" statement at the top is neccessary?
```bash
for f in about author example group param version
do
  eval "$f() { :; }"
done
unset f
```
This also seems to be part of the actual composure.sh file,
Just wondering if this was needed (as it already in the composure script we have sourced) or in fact a bug???
Once I know, I can look into the script further and attempt to fix this if needed.

**Comment by erichs** [comment]
Hi! Thanks for your interest in the project @mrazick and @5c0tt-b0t !

The reason that the `write()` command [hard-codes ](https://github.com/erichs/composure/blob/master/composure.sh#L526)the `cite` function is to support custom metadata attributes. You can define your own metadata, similar to `about`, `group`, `author`, etc, by doing something like:
